/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrgLegalRouteImport } from './routes/trg-legal'
import { Route as TrabajaConNosotrosRouteImport } from './routes/trabaja-con-nosotros'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as EquipoRouteImport } from './routes/equipo'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CompromisoRouteImport } from './routes/compromiso'
import { Route as ClientesYTestimoniosRouteImport } from './routes/clientes-y-testimonios'
import { Route as ActualidadRouteImport } from './routes/actualidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TerminalTerminalValparaisoRouteImport } from './routes/terminal/terminal-valparaiso'
import { Route as TerminalTerminalSanAntonioRouteImport } from './routes/terminal/terminal-san-antonio'
import { Route as ServiciosTransporteDeContenedoresRefrigeradosRouteImport } from './routes/servicios/transporte-de-contenedores-refrigerados'
import { Route as ServiciosTransporteDeContenedoresRouteImport } from './routes/servicios/transporte-de-contenedores'
import { Route as ServiciosConsolidadoYDesconsolidadoDeContenedoresRouteImport } from './routes/servicios/consolidado-y-desconsolidado-de-contenedores'
import { Route as ServiciosAlmacenajeDeCargaGeneralRouteImport } from './routes/servicios/almacenaje-de-carga-general'

const TrgLegalRoute = TrgLegalRouteImport.update({
  id: '/trg-legal',
  path: '/trg-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabajaConNosotrosRoute = TrabajaConNosotrosRouteImport.update({
  id: '/trabaja-con-nosotros',
  path: '/trabaja-con-nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipoRoute = EquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CompromisoRoute = CompromisoRouteImport.update({
  id: '/compromiso',
  path: '/compromiso',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesYTestimoniosRoute = ClientesYTestimoniosRouteImport.update({
  id: '/clientes-y-testimonios',
  path: '/clientes-y-testimonios',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualidadRoute = ActualidadRouteImport.update({
  id: '/actualidad',
  path: '/actualidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminalTerminalValparaisoRoute =
  TerminalTerminalValparaisoRouteImport.update({
    id: '/terminal/terminal-valparaiso',
    path: '/terminal/terminal-valparaiso',
    getParentRoute: () => rootRouteImport,
  } as any)
const TerminalTerminalSanAntonioRoute =
  TerminalTerminalSanAntonioRouteImport.update({
    id: '/terminal/terminal-san-antonio',
    path: '/terminal/terminal-san-antonio',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiciosTransporteDeContenedoresRefrigeradosRoute =
  ServiciosTransporteDeContenedoresRefrigeradosRouteImport.update({
    id: '/servicios/transporte-de-contenedores-refrigerados',
    path: '/servicios/transporte-de-contenedores-refrigerados',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiciosTransporteDeContenedoresRoute =
  ServiciosTransporteDeContenedoresRouteImport.update({
    id: '/servicios/transporte-de-contenedores',
    path: '/servicios/transporte-de-contenedores',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute =
  ServiciosConsolidadoYDesconsolidadoDeContenedoresRouteImport.update({
    id: '/servicios/consolidado-y-desconsolidado-de-contenedores',
    path: '/servicios/consolidado-y-desconsolidado-de-contenedores',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiciosAlmacenajeDeCargaGeneralRoute =
  ServiciosAlmacenajeDeCargaGeneralRouteImport.update({
    id: '/servicios/almacenaje-de-carga-general',
    path: '/servicios/almacenaje-de-carga-general',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/clientes-y-testimonios': typeof ClientesYTestimoniosRoute
  '/compromiso': typeof CompromisoRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/equipo': typeof EquipoRoute
  '/nosotros': typeof NosotrosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/trg-legal': typeof TrgLegalRoute
  '/servicios/almacenaje-de-carga-general': typeof ServiciosAlmacenajeDeCargaGeneralRoute
  '/servicios/consolidado-y-desconsolidado-de-contenedores': typeof ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute
  '/servicios/transporte-de-contenedores': typeof ServiciosTransporteDeContenedoresRoute
  '/servicios/transporte-de-contenedores-refrigerados': typeof ServiciosTransporteDeContenedoresRefrigeradosRoute
  '/terminal/terminal-san-antonio': typeof TerminalTerminalSanAntonioRoute
  '/terminal/terminal-valparaiso': typeof TerminalTerminalValparaisoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/clientes-y-testimonios': typeof ClientesYTestimoniosRoute
  '/compromiso': typeof CompromisoRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/equipo': typeof EquipoRoute
  '/nosotros': typeof NosotrosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/trg-legal': typeof TrgLegalRoute
  '/servicios/almacenaje-de-carga-general': typeof ServiciosAlmacenajeDeCargaGeneralRoute
  '/servicios/consolidado-y-desconsolidado-de-contenedores': typeof ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute
  '/servicios/transporte-de-contenedores': typeof ServiciosTransporteDeContenedoresRoute
  '/servicios/transporte-de-contenedores-refrigerados': typeof ServiciosTransporteDeContenedoresRefrigeradosRoute
  '/terminal/terminal-san-antonio': typeof TerminalTerminalSanAntonioRoute
  '/terminal/terminal-valparaiso': typeof TerminalTerminalValparaisoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualidad': typeof ActualidadRoute
  '/clientes-y-testimonios': typeof ClientesYTestimoniosRoute
  '/compromiso': typeof CompromisoRoute
  '/contacto': typeof ContactoRoute
  '/empresas': typeof EmpresasRoute
  '/equipo': typeof EquipoRoute
  '/nosotros': typeof NosotrosRoute
  '/trabaja-con-nosotros': typeof TrabajaConNosotrosRoute
  '/trg-legal': typeof TrgLegalRoute
  '/servicios/almacenaje-de-carga-general': typeof ServiciosAlmacenajeDeCargaGeneralRoute
  '/servicios/consolidado-y-desconsolidado-de-contenedores': typeof ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute
  '/servicios/transporte-de-contenedores': typeof ServiciosTransporteDeContenedoresRoute
  '/servicios/transporte-de-contenedores-refrigerados': typeof ServiciosTransporteDeContenedoresRefrigeradosRoute
  '/terminal/terminal-san-antonio': typeof TerminalTerminalSanAntonioRoute
  '/terminal/terminal-valparaiso': typeof TerminalTerminalValparaisoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualidad'
    | '/clientes-y-testimonios'
    | '/compromiso'
    | '/contacto'
    | '/empresas'
    | '/equipo'
    | '/nosotros'
    | '/trabaja-con-nosotros'
    | '/trg-legal'
    | '/servicios/almacenaje-de-carga-general'
    | '/servicios/consolidado-y-desconsolidado-de-contenedores'
    | '/servicios/transporte-de-contenedores'
    | '/servicios/transporte-de-contenedores-refrigerados'
    | '/terminal/terminal-san-antonio'
    | '/terminal/terminal-valparaiso'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualidad'
    | '/clientes-y-testimonios'
    | '/compromiso'
    | '/contacto'
    | '/empresas'
    | '/equipo'
    | '/nosotros'
    | '/trabaja-con-nosotros'
    | '/trg-legal'
    | '/servicios/almacenaje-de-carga-general'
    | '/servicios/consolidado-y-desconsolidado-de-contenedores'
    | '/servicios/transporte-de-contenedores'
    | '/servicios/transporte-de-contenedores-refrigerados'
    | '/terminal/terminal-san-antonio'
    | '/terminal/terminal-valparaiso'
  id:
    | '__root__'
    | '/'
    | '/actualidad'
    | '/clientes-y-testimonios'
    | '/compromiso'
    | '/contacto'
    | '/empresas'
    | '/equipo'
    | '/nosotros'
    | '/trabaja-con-nosotros'
    | '/trg-legal'
    | '/servicios/almacenaje-de-carga-general'
    | '/servicios/consolidado-y-desconsolidado-de-contenedores'
    | '/servicios/transporte-de-contenedores'
    | '/servicios/transporte-de-contenedores-refrigerados'
    | '/terminal/terminal-san-antonio'
    | '/terminal/terminal-valparaiso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualidadRoute: typeof ActualidadRoute
  ClientesYTestimoniosRoute: typeof ClientesYTestimoniosRoute
  CompromisoRoute: typeof CompromisoRoute
  ContactoRoute: typeof ContactoRoute
  EmpresasRoute: typeof EmpresasRoute
  EquipoRoute: typeof EquipoRoute
  NosotrosRoute: typeof NosotrosRoute
  TrabajaConNosotrosRoute: typeof TrabajaConNosotrosRoute
  TrgLegalRoute: typeof TrgLegalRoute
  ServiciosAlmacenajeDeCargaGeneralRoute: typeof ServiciosAlmacenajeDeCargaGeneralRoute
  ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute: typeof ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute
  ServiciosTransporteDeContenedoresRoute: typeof ServiciosTransporteDeContenedoresRoute
  ServiciosTransporteDeContenedoresRefrigeradosRoute: typeof ServiciosTransporteDeContenedoresRefrigeradosRoute
  TerminalTerminalSanAntonioRoute: typeof TerminalTerminalSanAntonioRoute
  TerminalTerminalValparaisoRoute: typeof TerminalTerminalValparaisoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trg-legal': {
      id: '/trg-legal'
      path: '/trg-legal'
      fullPath: '/trg-legal'
      preLoaderRoute: typeof TrgLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabaja-con-nosotros': {
      id: '/trabaja-con-nosotros'
      path: '/trabaja-con-nosotros'
      fullPath: '/trabaja-con-nosotros'
      preLoaderRoute: typeof TrabajaConNosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipo': {
      id: '/equipo'
      path: '/equipo'
      fullPath: '/equipo'
      preLoaderRoute: typeof EquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compromiso': {
      id: '/compromiso'
      path: '/compromiso'
      fullPath: '/compromiso'
      preLoaderRoute: typeof CompromisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes-y-testimonios': {
      id: '/clientes-y-testimonios'
      path: '/clientes-y-testimonios'
      fullPath: '/clientes-y-testimonios'
      preLoaderRoute: typeof ClientesYTestimoniosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualidad': {
      id: '/actualidad'
      path: '/actualidad'
      fullPath: '/actualidad'
      preLoaderRoute: typeof ActualidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/terminal-valparaiso': {
      id: '/terminal/terminal-valparaiso'
      path: '/terminal/terminal-valparaiso'
      fullPath: '/terminal/terminal-valparaiso'
      preLoaderRoute: typeof TerminalTerminalValparaisoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminal/terminal-san-antonio': {
      id: '/terminal/terminal-san-antonio'
      path: '/terminal/terminal-san-antonio'
      fullPath: '/terminal/terminal-san-antonio'
      preLoaderRoute: typeof TerminalTerminalSanAntonioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/transporte-de-contenedores-refrigerados': {
      id: '/servicios/transporte-de-contenedores-refrigerados'
      path: '/servicios/transporte-de-contenedores-refrigerados'
      fullPath: '/servicios/transporte-de-contenedores-refrigerados'
      preLoaderRoute: typeof ServiciosTransporteDeContenedoresRefrigeradosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/transporte-de-contenedores': {
      id: '/servicios/transporte-de-contenedores'
      path: '/servicios/transporte-de-contenedores'
      fullPath: '/servicios/transporte-de-contenedores'
      preLoaderRoute: typeof ServiciosTransporteDeContenedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/consolidado-y-desconsolidado-de-contenedores': {
      id: '/servicios/consolidado-y-desconsolidado-de-contenedores'
      path: '/servicios/consolidado-y-desconsolidado-de-contenedores'
      fullPath: '/servicios/consolidado-y-desconsolidado-de-contenedores'
      preLoaderRoute: typeof ServiciosConsolidadoYDesconsolidadoDeContenedoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios/almacenaje-de-carga-general': {
      id: '/servicios/almacenaje-de-carga-general'
      path: '/servicios/almacenaje-de-carga-general'
      fullPath: '/servicios/almacenaje-de-carga-general'
      preLoaderRoute: typeof ServiciosAlmacenajeDeCargaGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualidadRoute: ActualidadRoute,
  ClientesYTestimoniosRoute: ClientesYTestimoniosRoute,
  CompromisoRoute: CompromisoRoute,
  ContactoRoute: ContactoRoute,
  EmpresasRoute: EmpresasRoute,
  EquipoRoute: EquipoRoute,
  NosotrosRoute: NosotrosRoute,
  TrabajaConNosotrosRoute: TrabajaConNosotrosRoute,
  TrgLegalRoute: TrgLegalRoute,
  ServiciosAlmacenajeDeCargaGeneralRoute:
    ServiciosAlmacenajeDeCargaGeneralRoute,
  ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute:
    ServiciosConsolidadoYDesconsolidadoDeContenedoresRoute,
  ServiciosTransporteDeContenedoresRoute:
    ServiciosTransporteDeContenedoresRoute,
  ServiciosTransporteDeContenedoresRefrigeradosRoute:
    ServiciosTransporteDeContenedoresRefrigeradosRoute,
  TerminalTerminalSanAntonioRoute: TerminalTerminalSanAntonioRoute,
  TerminalTerminalValparaisoRoute: TerminalTerminalValparaisoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
